version: '3.9'

services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_USER=devuser
      - DB_NAME=himsaDB
      - DB_PASSWORD=mypassword
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=himsaDB
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=mypassword

volumes:
  dev-db-data: