---
name: Checks 
on: [push]
jobs:
  test-lints:
    name: Test and Lints 
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: checkout 
        uses: actions/checkout@v2

      - name: Test  
        run: docker-compose -f backend/docker-compose.yml run --rm app sh -c "python manage.py test"
